Posts are visible starting with newest
makersacademy/acebook-remote-april-2017 pull request #11
Opened 2017-05-30 10:32 UTC by anaalta

- added feature test checking the order of posting
- added orderly gem
- added post controller test to check the order of posts in the Post.all
- in posts/index, posts displayed in reverse
- added web helper for creating a post

2017-05-30 10:37 UTC, ddosque commented on spec/controllers/posts_controller_spec.rb
> +      post :create, params: { post: { message: 'My second post'} }
There is a gem called 'Factory Girl' that can make this a bit less brittle

2017-05-30 10:38 UTC, ddosque commented
Consider adding Factory Girl to manage your model fixtures. Otherwise :shipit: :shipit:

2017-05-30 14:32 UTC, FiddlersCode requested changes
Looks great!  A few small things:
posts_controller_spec: 
- remove commented code in lines 20 and 28
- line 31 looks to be missing and `end` or should it be part of a previous describe block?

spec/webhelpers:
We have updated the front-end so you once the front-end branch is merged, you'll need `click_button "New Post"` (note uppercase "p"

2017-05-30 14:34 UTC, milesillsley reviewed
I looked over this with Paula, can approve after changes.

2017-05-30 15:06 UTC, anaalta commented
@pmuldoon86, @milesillsley  thanks for the review! deleted the commented code, put an it under a describe block & clicking on the right New Post button now :)

2017-05-30 15:50 UTC, chrisjmit commented
@anaalta @BenNoonan1991 could you resolve the conflicts please so we can pull the repo for testing? thanks

2017-05-30 16:27 UTC, dbugsy approved these changes
One small change, then I'm happy for you to merge :shipit: :shipit:

2017-05-30 16:27 UTC, ddosque commented on spec/controllers/posts_controller_spec.rb
> +  FactoryGirl.define do
This should be in spec/factories/posts.rb as per: https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md#defining-factories

2017-05-31 04:49 UTC, danielemanuel approved these changes
:shipit:

2017-05-31 07:59 UTC, merged