Continuous deployment to Heroku using Travis CI
makersacademy/acebook-remote-april-2017 pull request #13
Opened 2017-05-30 13:39 UTC by chrisjmit

Hi all, Travis CI integration is now working with tests passing. We can't deploy to Heroku unless at master branch so not been able to test final deploy yet. 
Travis will approve the content of merged pull requests onto the Heroku server, making approved content live for each merge going forward.
Please could you review and ship as appropriate, as soon as you can? There's a couple of settings that can be really tricky for this and can prevent pull requests from happening.
Apologies for the faffs - it's really not been clear.
Thanks,
Jess & Chris

2017-05-30 14:33 UTC, sophieklm commented
:shipit:

2017-05-30 14:59 UTC, milesillsley requested changes
- remove one of the scripts in .travis.yml (line 5)
- there is a lonely # in Gemfile (line 9)
Code looks great, though Im not really sure how to test it or run the specs

2017-05-30 14:59 UTC, chrisjmit commented
test suggestion: try logging in to travis using github credentials, and from profile page adding the repo via organizations/makers academy. the branch test log should be for continuous-deployment

2017-05-30 15:03 UTC, JessicaBarclay commented
@milesillsley Thanks - changes made

2017-05-30 15:04 UTC, sblausten commented on app/views/posts/index.html.erb
> +  <p><%= format_url.return_formatted_url(post.message).html_safe %></p>
Can't figure out what this is doing. What's the change for?

2017-05-30 15:08 UTC, sblausten commented
@chrisjmit seems to be lots of code here adding new feature to posts that renders hyperlinks correctly in post display. Seems to be separate from Travis issue?

2017-05-30 15:09 UTC, Robert-G-J commented on app/models/classes/format_url.rb
> +  def return_formatted_url(post)
How does this relate to the Travis deployment? Looks like a different issue 😕

2017-05-30 15:10 UTC, chrisjmit commented on app/models/classes/format_url.rb
> +  def return_formatted_url(post)
this seems to be have been git added in via a code review of another branch. removed.

2017-05-30 15:11 UTC, chrisjmit commented
@sblausten this seems to be have been git added in via a code review of another branch. removed.

2017-05-30 15:17 UTC, dbugsy requested changes

2017-05-30 15:17 UTC, ddosque commented on .travis.yml
> +    secure: "Zhq+bAklzTvNgYeVKtA5mi3GmTYqEzCWCGclgOuK20D23Yi1iPkbcH09ricLABlk1Y7qFB8jGtbplrPbGrQQdhUW9sQ9OGLRlA/vJnMhU4IVK/ZM1EJCFZPZPv5Zbg4s8L2r0Gz7uIEOX05TYFcREZ5iice4Mq89rX/SgOVPswh3KCFq0BfxaLq111
Woah this should not be in git. What is that the api key for? Heroku? Are you 100% sure you need this in the yml file? I would suggest immediately changing this key in heroku, as it is now compromised.

2017-05-30 15:30 UTC, chrisjmit commented on .travis.yml
> +    secure: "Zhq+bAklzTvNgYeVKtA5mi3GmTYqEzCWCGclgOuK20D23Yi1iPkbcH09ricLABlk1Y7qFB8jGtbplrPbGrQQdhUW9sQ9OGLRlA/vJnMhU4IVK/ZM1EJCFZPZPv5Zbg4s8L2r0Gz7uIEOX05TYFcREZ5iice4Mq89rX/SgOVPswh3KCFq0BfxaLq111
@ddosque this isn't the api-key, but the travis gem encrypted api key. we installed the travis gem and ran travis encrypt (api-key-hash) --add deploy.api_key to generate this change. we've redone this and also done this manually to the same result. we'll look into another way of doing this for heroku if we're off the mark.

2017-05-30 16:02 UTC, chrisjmit commented on .travis.yml
> +    secure: "Zhq+bAklzTvNgYeVKtA5mi3GmTYqEzCWCGclgOuK20D23Yi1iPkbcH09ricLABlk1Y7qFB8jGtbplrPbGrQQdhUW9sQ9OGLRlA/vJnMhU4IVK/ZM1EJCFZPZPv5Zbg4s8L2r0Gz7uIEOX05TYFcREZ5iice4Mq89rX/SgOVPswh3KCFq0BfxaLq111
Reference:
https://docs.travis-ci.com/user/deployment/heroku/

2017-05-31 07:31 UTC, dbugsy approved these changes

2017-05-31 12:05 UTC, ddosque commented
Merge this anyway - it will prevent further red tests going into production. There is a ticket to fix the time issues.

2017-05-31 12:20 UTC, merged