Newsfeed current user
makersacademy/acebook-remote-april-2017 pull request #26
Opened 2017-06-01 15:19 UTC by DSeanGray

- used the built in devise method `authenticate_user!` before each post route method.
- used devise `sign_in` test helpers in controller tests.
- stubbed controller tests with a factory girl, factory for User.
- renamed the web helper `sign_in` method to `log_in` because it clashed with the devise built in method for `sign_in`.
- updated feature tests to sign up or sign in before viewing/making posts.

2017-06-01 15:40 UTC, FiddlersCode requested changes
Nice work!

2017-06-01 15:40 UTC, pmuldoon86 commented on app/controllers/posts_controller.rb
>    # include FormatUrl
remove comment

2017-06-01 15:40 UTC, pmuldoon86 commented on spec/controllers/posts_controller_spec.rb
>        expect(Post.find_by(message: "Hello, world!")).to be
Is there an expectation here?

2017-06-01 15:40 UTC, pmuldoon86 commented on spec/features/signed_in_users_see_newsfeed_spec.rb
> +  scenario 'user is not sign in and does not see the newsfeed' do
"signed in", not "sign"

2017-06-01 15:45 UTC, anaalta commented on spec/controllers/posts_controller_spec.rb
>        expect(Post.find_by(message: "Hello, world!")).to be
it was a default test, you just expect the object to exist. I don't think we need it anymore though

2017-06-01 16:14 UTC, sophieklm commented
Looks good, with Paula's changes actioned you may have my :shipit:

2017-06-01 16:54 UTC, JessicaBarclay commented
:shipit: from me - one suggestion may be that you announce the change from sign in to log in when merging, incase of problems down the line.

Looks great guys!

2017-06-02 11:22 UTC, chrisjmit approved these changes
:shipit:

2017-06-02 13:18 UTC, FiddlersCode approved these changes

2017-06-02 13:18 UTC, pmuldoon86 commented
:shipit:

2017-06-02 13:33 UTC, merged