Friends
makersacademy/acebook-remote-april-2017 pull request #27
Opened 2017-06-01 15:30 UTC by adamerdemer

- Adds friendships
- Added stub user profile to show friends
- Added find friends link
- Users are unique
- Cannot add yourself 
- Sign out button disappears after signing out (conditional)

2017-06-01 16:07 UTC, enonnai commented on app/controllers/friendships_controller.rb
> +    @friendship = current_user.friendships.build(friend_id: params[:friend_id])
If signed out, trying to add a friend returns a NoMethodError on line 3. Would probably need to return a flash notice saying you need to sign up/ log in to add friends.

2017-06-01 16:13 UTC, sophieklm commented on app/controllers/friendships_controller.rb
> +    @friendship = current_user.friendships.build(friend_id: params[:friend_id])
good spot

2017-06-01 16:25 UTC, anaalta commented on app/models/friendship.rb
> +  def check_user
When you try to add yourself, you get the same Error adding friend error

2017-06-01 16:35 UTC, anaalta requested changes
looks awesome! Great work! see comments for changes. also, instead of stubbing, maybe use Factory Girl gem?

2017-06-01 16:35 UTC, anaalta commented on app/views/users/index.html.erb
> +</ul>
Maybe add a if current_user (linked to the fact that you can see a list of emails and add friend buttons after you signed out)

2017-06-01 16:39 UTC, enonnai commented on app/controllers/friendships_controller.rb
> +      flash[:notice] = "You're not signed in!"
Functionality works just fine! I would just change the wording into something like 'Sign up or Log in to start adding friends' :)

2017-06-01 17:35 UTC, sophieklm commented on app/models/friendship.rb
> +  def check_user
I'm finding it difficult to implement flash errors to get the check user error to render, so I might have to hand over to someone else.

2017-06-01 22:02 UTC, JessicaBarclay commented
Looks Awesome, well done guys getting this going 💯

2017-06-02 09:01 UTC, JessicaBarclay commented
The only issue I could spot is that email address appear on the homepage when signed out? But this may be resolved when merged with other features that the Newsfeed guys worked on.

:shipit:

2017-06-02 09:06 UTC, chrisjmit commented
:shipit: possibly worth raising an issue for the add friend link displaying on home page when signed out, and a to do for friendship approvals so users can be added to both friend lists on approval. congrats!

2017-06-02 09:06 UTC, chrisjmit approved these changes

2017-06-02 09:20 UTC, anaalta commented
:shipit: 
isn't Factory Girl magical? :)

2017-06-02 09:20 UTC, anaalta approved these changes

2017-06-02 09:24 UTC, sophieklm commented on app/models/friendship.rb
> +  def check_user
Managed to update this

2017-06-02 09:26 UTC, enonnai commented
Great job guys! Would be nice to change 'Users' with 'Friends' to keep it consistent with the rest of the instructions and to have an error saying 'This user is already a friend' when trying to add a friend who has been added already, but for me it's a :shipit: !!!

2017-06-02 09:27 UTC, enonnai approved these changes

2017-06-02 09:44 UTC, merged