Like functionality
makersacademy/acebook-remote-april-2017 pull request #28
Opened 2017-06-01 15:39 UTC by JessicaBarclay

A User can like multiple posts, but only once per post. Feature does not update in real time, this is a separate feature(see Trello board for more info on WebSockets with Action Cable).

Functionality utilises [Acts as Votable gem](https://github.com/ryanto/acts_as_votable) which will 'Allow any model to be voted on, like/dislike, upvote/downvote, etc.'

You will notice in the views that the 'Like' function is rendered using partials, in a separate form view.

Would be great to get this merged, particularly if anyone wants build on this(such as liking photos for example).

Thank you in advance, 
Cristina and Jess

2017-06-01 17:10 UTC, FiddlersCode requested changes
![image](https://cloud.githubusercontent.com/assets/7489685/26691565/88544644-46f5-11e7-82b0-5c335603e9ec.png)
Wow, cool code, guys!
I assume this isn't meant to happen? :) . Is the number of likes supposed to increase after the like button has been clicked?  It doesn't for me, even after refresh.

2017-06-01 17:24 UTC, enonnai commented
Thanks for your feedback @pmuldoon86 . Yes, the number of likes is supposed to increase after a refresh only, as the real time update is a separate feature (there is a ticket about it in 'need research' column). Did you run `rake:db migrate` after pulling down pls?

2017-06-01 19:48 UTC, danielemanuel approved these changes
![screen shot 2017-06-01 at 20 44 33](https://cloud.githubusercontent.com/assets/24321855/26697905/9efc1550-470b-11e7-891c-40b972926e44.png)

User can like multiple posts, number of likes increases after page refresh, code looks DRY.
To be able to like a post you have to sign in as a user.

2017-06-01 19:49 UTC, danielemanuel commented
@pmuldoon86 , if you want to like a post you have to be sign in as a user.

2017-06-01 20:42 UTC, sophieklm commented
:shipit: 
nice simple implementation, realtime updates would be good, but a separate more complicated issue

2017-06-01 21:16 UTC, dbugsy approved these changes
Looks awesome consider small refactor in tests.

2017-06-01 21:16 UTC, ddosque commented on spec/web_helpers.rb
> +def sign_up_2
Looks like duplication. You could make the original sign_up method accept an argument for email and/or password.

2017-06-01 21:38 UTC, JessicaBarclay commented
@pmuldoon86 seems to be working for others - perhaps a db migration issue locally for you? Will take a look with you in the morning if you wish - throw me a Zoom 👍 

@sophieklm @danielemanuel cheers - real time updates would be great, but as you said Sophie seems quite complex. Thanks guys

@ddosque Refactored the web_helpers, thank you for the feedback

2017-06-01 21:39 UTC, enonnai commented
Thanks @danielemanuel ,@sophieklm and @ddosque!

2017-06-02 08:07 UTC, JessicaBarclay commented
@pmuldoon86 `bundle install` then `rails db:migrate` ?

2017-06-02 08:39 UTC, FiddlersCode approved these changes

2017-06-02 08:39 UTC, pmuldoon86 commented
Nice work, guys!  It ran for me after `bin/rails db:migrate RAILS_ENV=development`

2017-06-02 08:40 UTC, enonnai commented
thank you @pmuldoon86 ! But you didn't give us an inspector squirrel haha, just joking ;)

2017-06-02 08:45 UTC, merged