Photos comments
makersacademy/acebook-remote-april-2017 pull request #29
Opened 2017-06-01 17:01 UTC by jonathanelliot

Photos can be commented on. Refactored into partials.

2017-06-01 21:11 UTC, dbugsy requested changes
I don't see the reason for a PhotoComment model, better to reuse the existing comment class.

2017-06-01 21:11 UTC, ddosque commented on app/models/photo_comment.rb
> +  belongs_to :photo
This has the exact behaviour of the regular comment, so it's repeated code. There should be a better solution that is more dry.

2017-06-02 08:36 UTC, pmuldoon86 commented on app/models/photo_comment.rb
> +  belongs_to :photo
@ddosque we couldn't figure out how to reconcile database conflicts - e.g. comments have a relationship with posts and photocomments have a relationship with photos...we thought it was cleaner to have them clearly separated

2017-06-02 09:26 UTC, pmuldoon86 commented on app/models/photo_comment.rb
> +  belongs_to :photo
http://guides.rubyonrails.org/association_basics.html#polymorphic-associations

ah...

2017-06-02 09:27 UTC, pmuldoon86 commented on app/models/photo_comment.rb
> +  belongs_to :photo
https://stackoverflow.com/questions/22025288/comments-on-multiple-models

2017-06-02 09:54 UTC, closed without merging