Front end
makersacademy/acebook-remote-april-2017 pull request #4
Opened 2017-05-29 14:51 UTC by axcochrane

Please see first set of front-end changes. Created layout template.

Thanks!
S&P

2017-05-29 15:02 UTC, JessicaBarclay commented
:shipit:

Awesome!

2017-05-29 15:24 UTC, anaalta approved these changes

2017-05-29 15:24 UTC, anaalta commented
:shipit:

2017-05-29 15:29 UTC, adc17 commented
A couple of points:
—Look into using partials.
—What is all this `welcome` stuff?

2017-05-29 15:37 UTC, AlexChalk requested changes
A couple of requests:
—DRY out code with partials (see this page: http://guides.rubyonrails.org/layouts_and_rendering.html).
—Explain what all the welcome stuff is in your pr message (ideally in your commit messages next time).

2017-05-29 16:17 UTC, chrisjmit commented
:shipit:

2017-05-29 16:39 UTC, axcochrane commented
Thanks guys. We've made a couple of changes:

1 - abstracted _header and _footer partials from application layout template. 
2 - Create a new button class in our CSS to style the 'new post' button

Re the Welcome controller and views, I believe that's just the standard rails terminology for what we have previously referred to as index. So in essence, we've just created a path and a view for the / route.

Thanks!
S&P

2017-05-29 17:43 UTC, adc17 commented
Hey, would definitely put stuff like `DOCTYPE` tags into partials. 

I think `/` is just defined on line 6 of your `config/routes` (the `root` line). But if `welcome` is the standard name for the stuff used to serve that page, and it's a RESTful name, etc., that's fine.

2017-05-29 17:47 UTC, dbugsy requested changes
A couple of un-railsy things in here, otherwise awesome!

Be careful including images in the main directory - they go into the git repo hang around even after they are deleted. Better to find an external repository.

2017-05-29 17:47 UTC, ddosque commented on app/assets/stylesheets/application.css
> +require_relative styles.css
This is not needed - your styles.css will be required and compiled automatically by the line `= require_tree .`.

2017-05-29 17:47 UTC, ddosque commented on spec/helpers/welcome_helper_spec.rb
> +end
looks like an unnecessarily generated file - check for these and delete them before merging.

2017-05-29 17:47 UTC, ddosque commented on app/views/posts/index.html.erb
> +  <button class='button'>New Post</button>
http://api.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html#method-i-button_to

2017-05-29 17:48 UTC, ddosque commented
I think there is a failing test in this PR. Make sure to find it and fix it before merging.

2017-05-30 14:51 UTC, Robert-G-J commented
Is the test Dan mentioned still failing @axcochrane ?

2017-05-30 15:10 UTC, pmuldoon86 commented
@Robert-G-J tests all passing, FINALLY :)

2017-05-30 15:19 UTC, ddosque commented
:shipit: :shipit:

2017-05-31 10:38 UTC, merged