Modeling users passwords
makersacademy/acebook-remote-april-2017 pull request #5
Opened 2017-05-29 14:59 UTC by adamerdemer

Added in secure passwords

2017-05-29 17:13 UTC, dbugsy requested changes
I'm interested in why you are building this manually - devise gem would automate this. Design decisions should be added to the PR to avoid questions like this.

2017-05-29 17:13 UTC, ddosque commented on spec/models/user_spec.rb
> +		it "checks user has a email attribute" do
Indentation needs to be fixed

2017-05-29 17:14 UTC, ddosque commented
Please move trello ticket into the correct column @adamerdemer @Robert-G-J

2017-05-29 21:11 UTC, adamerdemer commented
@ddosque I used this method because the link on the ticket said to not use devise in your first rails project. https://github.com/plataformatec/devise#starting-with-rails

We followed the instructions via Micheal Hartl's book.

2017-05-30 14:52 UTC, sblausten commented
:shipit:

2017-05-30 14:55 UTC, Robert-G-J commented
@adamerdemer @danielemanuel Is this pull request still valid? Or has it been overwritten by your work on Devise?

2017-05-30 15:01 UTC, closed without merging