Post date time feature
makersacademy/acebook-remote-april-2017 pull request #6
Opened 2017-05-29 16:36 UTC by jonathanelliot

Main Changes

- added `config.time_zone = "London"` to all config/environments
- passed `Time.now` as parameter to `posts` when created
- format time method in `models/post.rb`
- add formatted time to `posts Timeline`

2017-05-29 17:07 UTC, ddosque commented on app/models/post.rb
> +    return "posted at #{self.created_at.strftime('%H:%M')} on #{self.created_at.strftime('%d/%m/%Y')}"
This shouldn't be in the model - it is presentation logic. Prefer a PostPresenter object instead.

2017-05-29 17:08 UTC, dbugsy requested changes

2017-05-29 17:08 UTC, ddosque commented on spec/features/user_can_submit_posts_spec.rb
> +  end
Duplicates the test above. Refactor to remove duplication.

2017-05-30 11:09 UTC, jonathanelliot commented
Requested changes made - PostPresenter module added

2017-05-30 11:44 UTC, dbugsy requested changes

2017-05-30 11:44 UTC, ddosque commented on app/controllers/posts_controller.rb
> +    params.require(:post).permit(:message, created_at: Time.now)
I don't think you need to add this to the permit, as the timestamp will be added at the model layer.

2017-05-30 11:44 UTC, ddosque commented on app/models/post_presenter.rb
> +end
Looks great! I'd probably put it into 'app/presenters/post_presenter.rb'.

A class is more commonly used:

```ruby
class PostPresenter
  def initialize(post)
    @post = post
  end
  
  def timestamp
    post.created_at.strftimeblablablabl
  end
end

```

2017-05-30 11:44 UTC, ddosque commented on app/models/post_presenter.rb
> +end
The "posted at etc" is purely view based, and should appear in the view template if at all possible.

2017-05-30 11:44 UTC, ddosque commented on app/models/post_presenter.rb
> +    return "posted at #{self.created_at.strftime('%H:%M')} on #{self.created_at.strftime('%d/%m/%Y')}"
implicit return in ruby

2017-05-30 11:57 UTC, jonathanelliot commented
Requested changes made

2017-05-30 12:00 UTC, jonathanelliot commented
Also don't understand why Travis CI build is failing. Any ideas?

2017-05-30 14:11 UTC, axcochrane commented
Hey - as we just chatted about. Could potentially make separate methods for datestamp and timestamp so they can be reused elsewhere if needed.

```
class PostPresenter
  def initialize(post)
    @post = post
  end
  
  def timestamp
    post.created_at.strftime('%H:%M')
  end

  def datestamp
    post.created_at.strftime('%d/%m/%Y')
  end
end
```

2017-05-30 14:12 UTC, axcochrane requested changes
Hey - as we just chatted about. Could potentially make separate methods for datestamp and timestamp so they can be reused elsewhere if needed.
```
class PostPresenter
  def initialize(post)
    @post = post
  end
  
  def timestamp
    post.created_at.strftime('%H:%M')
  end

  def datestamp
    post.created_at.strftime('%d/%m/%Y')
  end
end
```

2017-05-30 14:41 UTC, jonathanelliot commented
Display logic separated to /views - still using a module over a class as cannot extract methods from class.

2017-05-30 15:20 UTC, dbugsy approved these changes

2017-05-30 15:21 UTC, ddosque commented
You would just use the presenter class in the controller instead of the Post class, but if the module pattern works for you, I'm happy to try it.

2017-05-30 15:24 UTC, anaalta approved these changes

2017-05-30 15:24 UTC, adc17 commented
Wicked guys :shipit:

2017-05-30 15:24 UTC, anaalta commented
:shipit:  :) nice

2017-05-30 15:25 UTC, AlexChalk approved these changes
Nice :shipit:

2017-05-30 15:31 UTC, merged